/*
TODO: 
1: add action event for radio buttons (and set default choice)
2: use BruteForceCracker object to crack the entered hash
3: test
*/
package bruteforcepassworkcracker;

/**
 *
 * @author p7-robinson
 */
public class Gui extends javax.swing.JFrame {

    
    private BruteForceCracker cracker;
    /**
     * Creates new form Gui
     */
    public Gui() {
        cracker = new BruteForceCracker();
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        bCrackPassword = new javax.swing.JButton();
        bClear = new javax.swing.JButton();
        tfEnterHash = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        taOutputPassword = new javax.swing.JTextArea();
        rbLettersLower = new javax.swing.JRadioButton();
        rbNums = new javax.swing.JRadioButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        tfEnterLength = new javax.swing.JTextField();
        bSetLength = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        bCrackPassword.setText("Crack");
        bCrackPassword.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bCrackPasswordActionPerformed(evt);
            }
        });

        bClear.setText("Clear");
        bClear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bClearActionPerformed(evt);
            }
        });

        tfEnterHash.setText("Enter hash");

        taOutputPassword.setColumns(20);
        taOutputPassword.setRows(5);
        jScrollPane1.setViewportView(taOutputPassword);

        rbLettersLower.setText("Lowercase letters");
        rbLettersLower.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rbLettersLowerActionPerformed(evt);
            }
        });

        rbNums.setText("Nums only");
        rbNums.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rbNumsActionPerformed(evt);
            }
        });

        jLabel1.setText("Select alphabet");

        jLabel2.setText("Select maximum length");

        tfEnterLength.setText("Enter length");
        tfEnterLength.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tfEnterLengthActionPerformed(evt);
            }
        });

        bSetLength.setText("Set");
        bSetLength.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bSetLengthActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(53, 53, 53)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(tfEnterLength, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(bSetLength))
                    .addComponent(jLabel2)
                    .addComponent(rbNums, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(tfEnterHash)
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(bCrackPassword, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                            .addComponent(bClear, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 167, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(rbLettersLower))
                .addContainerGap(161, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel2)
                .addGap(6, 6, 6)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tfEnterLength, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(bSetLength))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(rbLettersLower)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(rbNums)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 4, Short.MAX_VALUE)
                .addComponent(tfEnterHash, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(bClear)
                    .addComponent(bCrackPassword))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(23, 23, 23))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void bClearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bClearActionPerformed
        // clear text
        tfEnterHash.setText("");
        taOutputPassword.setText("");
    }//GEN-LAST:event_bClearActionPerformed

    private void bCrackPasswordActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bCrackPasswordActionPerformed
        
        //1. Get password from text field
        String result = cracker.crack_password(tfEnterHash.getText());
        if (result != null)
        {
            taOutputPassword.setText("Password is: " + result);
        }
        else
        {
            taOutputPassword.setText("Password not found");
        }
        //2. 
        
    }//GEN-LAST:event_bCrackPasswordActionPerformed

    private void tfEnterLengthActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tfEnterLengthActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tfEnterLengthActionPerformed

    private void bSetLengthActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bSetLengthActionPerformed
        try
        {
            cracker.set_length(Integer.parseInt(tfEnterLength.getText()));
        }
        catch (Exception e)
        {
            System.out.println("Error [bSetLengthActionPerformed] : invalid input");
            taOutputPassword.setText("Error: length must be an integer value, please try again");
        }
    }//GEN-LAST:event_bSetLengthActionPerformed

    private void rbLettersLowerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rbLettersLowerActionPerformed
        boolean checked = rbLettersLower.isSelected();
        if (checked)
        {
            rbNums.setSelected(false);
            cracker.set_alphabet(1);
        }
        else
        {
            cracker.set_alphabet(-1);
        }
    }//GEN-LAST:event_rbLettersLowerActionPerformed

    private void rbNumsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rbNumsActionPerformed
        boolean checked = rbNums.isSelected();
        if (checked)
        {
            rbLettersLower.setSelected(false);
            cracker.set_alphabet(2);
        }
        else
        {
            cracker.set_alphabet(-1);
        }
    }     
    }//GEN-LAST:event_rbNumsActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Gui.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Gui.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Gui.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Gui.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Gui().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bClear;
    private javax.swing.JButton bCrackPassword;
    private javax.swing.JButton bSetLength;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JRadioButton rbLettersLower;
    private javax.swing.JRadioButton rbNums;
    private javax.swing.JTextArea taOutputPassword;
    private javax.swing.JTextField tfEnterHash;
    private javax.swing.JTextField tfEnterLength;
    // End of variables declaration//GEN-END:variables
}
